In [1]:
#Siempre lo primero que deb hacer es importar pandas y numpy
import pandas as pd
import numpy as np

In [11]:
#ahora subimos el archivo desde google drive , ya no tenemos que logearnos de nuevo
df_estudiantes=pd.read_csv("/content/drive/MyDrive/StudentsPerformance.csv")
df_estudiantes

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [12]:
#simagomos con la creacion de columnas usando el metodo assign o el metodo insert
#si quiero agregar varias columnas uso assing y tambien si quiero sobreescribir una columna

In [15]:
#creamos notas de fisica y filosofia aleatorias y las guardamos en variables
filosofia_score=np.random.randint(1, 100, size=1000)
Fisica_score=np.random.randint(1,100, size=1000)

In [17]:
#ahora le pondre un indice a cada fila para saber donde va en el dataframe
filosofia_nota=pd.Series(filosofia_score, index=np.arange(0,1000))
fisica_nota=pd.Series(Fisica_score, index=np.arange(0,1000))

In [19]:
#Ahora lo que voy a hacer es poner las nuevas columnas a mi dataframe usando asing
df_estudiantes.assign(filosofia_score=filosofia_nota,Fisica_score=fisica_nota)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,filosofia_score,Fisica_score
0,female,group B,bachelor's degree,standard,none,72,72,74,27,89
1,female,group C,some college,standard,completed,69,90,88,70,70
2,female,group B,master's degree,standard,none,90,95,93,40,44
3,male,group A,associate's degree,free/reduced,none,47,57,44,26,44
4,male,group C,some college,standard,none,76,78,75,26,76
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,59,19
996,male,group C,high school,free/reduced,none,62,55,55,65,87
997,female,group C,high school,free/reduced,completed,59,71,65,39,4
998,female,group D,some college,standard,completed,68,78,77,59,72
999,female,group D,some college,free/reduced,none,77,86,86,88,57

In [22]:
df_estudiantes=df_estudiantes.assign(filosofia_score=filosofia_nota,Fisica_score=fisica_nota)

In [23]:
df_estudiantes

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,filosofia_score,Fisica_score
0,female,group B,bachelor's degree,standard,none,72,72,74,27,89
1,female,group C,some college,standard,completed,69,90,88,70,70
2,female,group B,master's degree,standard,none,90,95,93,40,44
3,male,group A,associate's degree,free/reduced,none,47,57,44,26,44
4,male,group C,some college,standard,none,76,78,75,26,76
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,59,19
996,male,group C,high school,free/reduced,none,62,55,55,65,87
997,female,group C,high school,free/reduced,completed,59,71,65,39,4
998,female,group D,some college,standard,completed,68,78,77,59,72
999,female,group D,some college,free/reduced,none,77,86,86,88,57

In [30]:
#ahora vamos a usar el metodo insert , el metodo insert es diferente porque me permite especificar donde voy a colocar la columna
#al usar el metodo insert debemos tener cuidado por que no me devuelve copias si no que el cambio queda hecho de una vez
df_estudiantes.insert(1, "ED_SCORE", fisica_nota)
df_estudiantes

ValueError: cannot insert ED_SCORE, already exists

In [25]:
df_estudiantes

,gender,ED_SCORE,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,filosofia_score,Fisica_score
0,female,89,group B,bachelor's degree,standard,none,72,72,74,27,89
1,female,70,group C,some college,standard,completed,69,90,88,70,70
2,female,44,group B,master's degree,standard,none,90,95,93,40,44
3,male,44,group A,associate's degree,free/reduced,none,47,57,44,26,44
4,male,76,group C,some college,standard,none,76,78,75,26,76
...,...,...,...,...,...,...,...,...,...,...,...
995,female,19,group E,master's degree,standard,completed,88,99,95,59,19
996,male,87,group C,high school,free/reduced,none,62,55,55,65,87
997,female,4,group C,high school,free/reduced,completed,59,71,65,39,4
998,female,72,group D,some college,standard,completed,68,78,77,59,72
999,female,57,group D,some college,free/reduced,none,77,86,86,88,57